--------------------------------------------------------
--  Arquivo criado - segunda-feira-outubro-13-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPRESAS_LOG
--------------------------------------------------------

  CREATE TABLE "RM566901"."EMPRESAS_LOG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(30 BYTE), 
	"DOSE" VARCHAR2(30 BYTE), 
	"QUATORZE" VARCHAR2(30 BYTE), 
	"VINTE_E_DOIS" VARCHAR2(30 BYTE), 
	"TRINTA" VARCHAR2(30 BYTE), 
	"QUARENTA_E_DOIS" VARCHAR2(30 BYTE), 
	"CUSTO_CURTO" FLOAT(126), 
	"CUSTO_LONGO" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
REM INSERTING into RM566901.EMPRESAS_LOG
SET DEFINE OFF;
Insert into RM566901.EMPRESAS_LOG (ID,NOME,DOSE,QUATORZE,VINTE_E_DOIS,TRINTA,QUARENTA_E_DOIS,CUSTO_CURTO,CUSTO_LONGO) values ('1','Log1','0','ok','0','0','ok','125','360');
Insert into RM566901.EMPRESAS_LOG (ID,NOME,DOSE,QUATORZE,VINTE_E_DOIS,TRINTA,QUARENTA_E_DOIS,CUSTO_CURTO,CUSTO_LONGO) values ('2','log2','0','0','ok','ok','0','128','355');
Insert into RM566901.EMPRESAS_LOG (ID,NOME,DOSE,QUATORZE,VINTE_E_DOIS,TRINTA,QUARENTA_E_DOIS,CUSTO_CURTO,CUSTO_LONGO) values ('3','log3','ok','ok','0','0','0','150','358');
Insert into RM566901.EMPRESAS_LOG (ID,NOME,DOSE,QUATORZE,VINTE_E_DOIS,TRINTA,QUARENTA_E_DOIS,CUSTO_CURTO,CUSTO_LONGO) values ('4','log4','0','0','ok','ok','0','130','350');
Insert into RM566901.EMPRESAS_LOG (ID,NOME,DOSE,QUATORZE,VINTE_E_DOIS,TRINTA,QUARENTA_E_DOIS,CUSTO_CURTO,CUSTO_LONGO) values ('5','log5','ok','0','ok','ok','0','220','300');
Insert into RM566901.EMPRESAS_LOG (ID,NOME,DOSE,QUATORZE,VINTE_E_DOIS,TRINTA,QUARENTA_E_DOIS,CUSTO_CURTO,CUSTO_LONGO) values ('6','log6','ok','0','0','ok','ok','98','320');
--------------------------------------------------------
--  DDL for Index SYS_C005958668
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM566901"."SYS_C005958668" ON "RM566901"."EMPRESAS_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table EMPRESAS_LOG
--------------------------------------------------------

  ALTER TABLE "RM566901"."EMPRESAS_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RM566901"."EMPRESAS_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
